---
- name: Include variables
  include_vars: "auth_mellon.yml"

- name: Restore SP metadata
  include_role:
    name: backup_and_restore
    tasks_from: restore
  vars:
    backup_path: "{{ mellon_backup_path }}"
    backup_filename: "{{ mellon_backup_name }}"

- name: Create metadata
  become: false
  script: >
    scripts/mellon_create_metadata.sh -d {{ output_dir }}
    -n {{ entity_id }} {{ endpoint_url }} {{ given_name }}
    {{ surname }} {{ email_contact }} {{ organisation }}
    {{ sp_protocol }}{{ sp_fqdn }} '{{ service_description }}'
    '{{ service_display_name }}'
  args:
    creates: "{{ output_dir }}/{{ hostname }}.{{ domain_name }}.xml"
  register: new_metadata

- name: Backup SP metadata
  include_role:
    name: backup_and_restore
    tasks_from: backup
  vars:
    backup_path: "{{ mellon_backup_path }}"
    backup_filename: "{{ mellon_backup_name }}"

- name: Create a directory where auth_mellon can store data
  file:
    path: /var/cache/mod_auth_mellon_postdata
    state: directory
    owner: www-data
    mode: 0755
  when: new_metadata|changed

- name: Create a directory metadata for auth_mellon is stored
  file:
    path: /etc/apache2/mellon
    state: directory
    owner: www-data
    mode: 0700
  when: new_metadata|changed

- name: Copy auth_mellon files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ auth_mellon_templates }}"
  notify:
    - Restart Apache
  when: new_metadata|changed

- name: Copy SP metadata, key and cert
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: True
    owner: www-data
    mode: "{{ item.mode }}"
  with_items: "{{ sp_files }}"
  when: new_metadata|changed
  notify:
    - Restart Apache
