---

- name: Include variables
  include_vars: sshd.yml

- name: Perform apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 360
  become: Yes

- name: Ensure ldap client is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ldap-utils
  become: yes

- name: Copy authorized key script
  copy:
    src: roles/sshd/files/get-authorized-keys.sh
    dest: /usr/local/bin/
    owner: nobody
    group: nogroup
    mode: 0700

- name: Copy sshd related files
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart sshd

- name: Configure LDAP client
  template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    mode: 0644
    owner: root
    group: root

- name: Copy the CA certificate
  copy:
    src: ca/{{ domain_name }}/certs/{{ sp_fqdn }}.pem
    dest: /usr/share/ca-certificates/{{ sp_fqdn }}.pem

- name: Ensure the CA certificate is installed
  become_user: root
  become: True
  command: update-ca-certificates
  tags:
    - skip_ansible_lint
